### ISSUE TITLE
no longer able to load on the new firefox mobile and dead link on web store for chrome

### ISSUE THREAD

**Issue by zippyflyer** [pvrs12/Anesidora#62] opened 2020-09-27 03:59 UTC
no longer able to load on the new firefox mobile and dead link on web store for chrome

**Comment by hucario** [comment] 2020-09-28 13:33
Duplicate of #61 

> Hi, you're right. I actually received a copyright infringement notice from Pandora requesting that I take it down.
> 
> I suspect that with some changes and a legal battle it may be able to be re-published, however this isn't something that I am willing to do.

**Comment by drnick88101** [comment] 2020-10-12 01:37
what happens when you try to load on firefox? do you get an error or something?

**Comment by angelhdz** [comment] 2020-11-10 08:10
Yup. I use this extension all the time. I reset Windows 10 recently, and when I was to install it, it's gone. It doesn't appear in Google search results. Not on the chrome extensions store either. What happened!?

**Comment by zippyflyer** [comment] 2020-11-10 08:55
It works fine on firefox for pc, but for the firefox mobile, it just says not available yet and is grayed out, no option to configure anything or load it.
managed to load the chrome extension on kiwi browser for mobile but it crashes the browser from time to time.

**Comment by pvrs12** [comment] 2020-11-10 16:02
Mozilla no longer allows for arbitrary extensions to be installed on
Firefox mobile. Instead they only allow for "Recommended extensions"

https://support.mozilla.org/en-US/kb/recommended-extensions-program

This currently only includes 11 extensions:
https://addons.mozilla.org/en-US/android/

It's entirely out of my control

**Closed as completed by pvrs12** 2020-11-10 16:02 UTC
